spring:
  redis:
  #    host: localhost
  #    port: 6379
  #    password: 123
      host: 120.53.17.64
      port: 6379
      password: cihon
      spring.redis.pool.max-active: 8
      ## 连接池最大阻塞等待时间（使用负值表示没有限制）
      spring.redis.pool.max-wait: -1
      ## 连接池中的最大空闲连接
      spring.redis.pool.max-idle: 8
      ## 连接池中的最小空闲连接
      spring.redis.pool.min-idle: 0
      ## 连接超时时间（毫秒）
      spring.redis.timeout: 0

  datasource:
      driver-class-name: com.mysql.jdbc.Driver
  #    username: root
  #    password: root
  #    url: jdbc:mysql://localhost:3306/gx?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true&tinyInt1isBit=false
      username: root
      password: Cihon!@#123
      url: jdbc:mysql://120.53.17.64:3306/gx?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true&tinyInt1isBit=false

  #双数据采用Druid 多数据源区分主从方式，即配置主库的机器高配置，把核心高频的数据放在主库上；把次要的数据放在从库
  #DruidDriver 代理 Driver，能够提供基于 Filter－Chain 模式的插件体系。
  #DruidDataSource 高效可管理的数据库连接池
master:
      datasource:
            driver-class-name: com.mysql.jdbc.Driver
        #    username: root
        #    password: root
        #    url: jdbc:mysql://localhost:3306/gx?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true&tinyInt1isBit=false
            username: root
            password: Cihon!@#123
            url: jdbc:mysql://120.53.17.64:3306/gx?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true&tinyInt1isBit=false

cluster:
      datasource:
            driver-class-name: com.mysql.jdbc.Driver
                #    username: root
                #    password: root
                #    url: jdbc:mysql://localhost:3306/gx?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true&tinyInt1isBit=false
            username: root
            password: Cihon!@#123
            url: jdbc:mysql://120.53.17.64:3306/dim?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true&tinyInt1isBit=false

es:
  host: es-oad51pug.public.tencentelasticsearch.com
  port: 9200
  scheme: https
  esDataSource:
      url: jdbc:es://${es.scheme}://${es.host}:${es.port}
      driver-class-name: org.elasticsearch.xpack.sql.jdbc.EsDriver
      mapperLocations: classpath:/es/mapper/*.xml
      configLocation: classpath:/config/elastic-mybatis.xml
      username: elastic
      password: guangqi@2020

elasticsearch:
  port: ${es.port}
  host: ${es.host}:${elasticsearch.port}
  username: ${es.username}
  password: ${es.password}
  scheme: ${es.scheme}
